# Generated by Django 5.0.3 on 2024-03-16 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.JSONField(default={'action_intialization': 0, 'domains': {}}),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('query_keys', models.JSONField(default=list)),
                ('time_spend', models.PositiveIntegerField(default=10)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
    ]
