# Generated by Django 5.0.3 on 2024-03-16 09:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_user_info_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='status',
            new_name='is_relevant',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.JSONField(default=core.models.generate_default_fields),
        ),
    ]
